services:

  postgres:
    image: postgres:16
    container_name: database-postgres-ventas
    environment:
      POSTGRES_DB: MicroVentasDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres-ventas-data:/var/lib/postgresql/data
    networks:
      - microservicios-net

  microventas:
    image: microventas-api:2.0
    container_name: microventas-api
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-postgres-ventas:5432/MicroVentasDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq-microservicios
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    ports:
      - "8082:8080"
    networks:
      - microservicios-net

volumes:
  postgres-ventas-data:

networks:
  microservicios-net:
    external: true
    name: appdistri2026_2_microservicios-net